### ISSUE TITLE
ISI function ValueError

### ISSUE THREAD

**Issue by lungsi** [NeuralEnsemble/elephant#116]
**Given spikes**
`>>> spikes
<SpikeTrain(array([  503.8  ,   520.05 ,   536.325,   552.625,   568.925,   585.225,
         601.575,   617.95 ,   634.325,   650.725,   667.15 ,   683.575,
         700.05 ,   716.525,   733.025,   749.55 ,   766.075,   782.625,
         799.175,   815.75 ,   832.35 ,   848.95 ,   865.575,   882.225,
         898.9  ,   915.575,   932.275,   949.   ,   965.75 ,   982.5  ,
         999.25 ,  1016.025,  1032.825,  1049.65 ,  1066.5  ,  1083.35 ,
        1100.225,  1117.125,  1134.025,  1150.95 ,  1167.9  ,  1184.875,
        1201.85 ,  1218.85 ,  1235.875,  1252.9  ,  1269.95 ,  1287.025,
        1304.1  ,  1321.175,  1338.275,  1355.4  ,  1372.525,  1389.675,
        1406.85 ,  1424.05 ,  1441.25 ,  1458.5  ,  1475.75 ,  1493.   ]) * ms, [500.0, 1500.0])>`
**When I run the elephant.statistics.isi to get the inter-spike interval**
`isi(spikes)`
**I get**
`>>> isi(spikes)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/miniconda2/lib/python2.7/site-packages/elephant/statistics.py", line 49, in isi
    intervals = np.diff(spiketrain, axis=axis)
  File "~/miniconda2/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1578, in diff
    return a[slice1]-a[slice2]
  File "~/miniconda2/lib/python2.7/site-packages/neo/core/spiketrain.py", line 461, in __sub__
    _check_time_in_range(spikes - time, self.t_start, self.t_stop)
  File "~/miniconda2/lib/python2.7/site-packages/neo/core/spiketrain.py", line 66, in _check_time_in_range
    (value, t_start))`
`ValueError: The first spike ([ 16.25   16.275  16.3    16.3    16.3    16.35   16.375  16.375  16.4
  16.425  16.425  16.475  16.475  16.5    16.525  16.525  16.55   16.55
  16.575  16.6    16.6    16.625  16.65   16.675  16.675  16.7    16.725
  16.75   16.75   16.75   16.775  16.8    16.825  16.85   16.85   16.875
  16.9    16.9    16.925  16.95   16.975  16.975  17.     17.025  17.025
  17.05   17.075  17.075  17.075  17.1    17.125  17.125  17.15   17.175
  17.2    17.2    17.25   17.25   17.25 ] ms) is before t_start (500.0)
`
**_Why am I getting this error?_
Clearly,**
`>>> spikes[0]`
`array(503.79999999967873) * ms`
**does not start before** `t_start(500.0)`

**Comment by mdenker** [comment]
Hi Lungsi, I think this error has been fixed in the current elephant master branch. I can reproduce your error with elephant 0.4.1, but not with the master branch using the following minimal example:
```python
>>> k=neo.SpikeTrain([1, 2, 502, 506, 1000]*pq.ms, t_start=0*pq.ms, t_stop=2000*pq.ms)
>>> l=k.time_slice(500*pq.ms, 1500*pq.ms)
>>> s.isi(l)
Out: array([   4.,  494.]) * ms
```

Indeed, as far as I recall this had to do with Neo introducing checks for spike times, therefore the SpikeTrain object is no longer used to return ISI values.
