### ISSUE TITLE
Deduplicate requirement information

### ISSUE THREAD

**Issue by healther** [NeuralEnsemble/elephant#158]
Currently requirements are specified both directly in `setup.py` as well as in `requirements.txt`.

Would it be possible to parse `requirements.txt` with something like (would require removal of commented out lines in `requirements.txt`)
```
with open('requirements.txt') as fp:
    install_requires = fp.read()

setup(install_requires=install_requires, ...)
```
rather than have two different locations for the same information?

**Comment by healther** [comment]
cc @muffgaga @schmitts

**Comment by muffgaga** [comment]
BTW. the software specified in the travis job seems to be slightly different (optional dependency on `pandas` version) from `requirements.txt`.

**Comment by alperyeg** [comment]
@healther  @muffgaga, I completely agree. I can do it, otherwise feel free to contribute. Of course, we are happy for any other suggestions for improving the setup and ci routines (see e.g. #129).

**Comment by rgerkin** [comment]
@healther @muffgaga @alperyeg To make sure this works in all cases, consider looking at my implementation in SciUnit [here](https://github.com/scidash/sciunit/blob/master/setup.py).  This handles pip <=9 vs pip 10, and parses some edge cases where a valid line in `requirements.txt` is not a valid `install_requires` list item.  It also supports `--process-dependency-links` if we ever need that.  Lastly, don't forget to add `requirements.txt` to a new `MANIFEST.in` file, otherwise `requirements.txt` will not get included in the pypi release and setup will fail because it won't be able to find it.

**Comment by healther** [comment]
I'll try to get you a PR sometime next week

**Comment by alperyeg** [comment]
> Would it be possible to package the `fim.so`s directly with the elephant sources
I would not like to change that. The `fim.so` is directly downloaded from Christian Borgelts HP (the developer and maintainer of the frequent itemset algorithm we use) and we do not want to ship all the files. Besides, there is a fall-back version in  pure but slow python if the files cannot be accessed.

**Comment by healther** [comment]
The problem is that right now the following will happen if you don't have an internet connection when doing `python setup.py install`

```
$ python setup.py install
Traceback (most recent call last):
  File "/Users/healther/.pyenv/versions/3.5.2/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/Users/healther/.pyenv/versions/3.5.2/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/Users/healther/.pyenv/versions/3.5.2/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/Users/healther/.pyenv/versions/3.5.2/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/Users/healther/.pyenv/versions/3.5.2/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/Users/healther/.pyenv/versions/3.5.2/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/Users/healther/.pyenv/versions/3.5.2/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/Users/healther/.pyenv/versions/3.5.2/lib/python3.5/socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/Users/healther/.pyenv/versions/3.5.2/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    'elephant/spade_src/fim.so')
  File "/Users/healther/.pyenv/versions/3.5.2/lib/python3.5/urllib/request.py", line 188, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Users/healther/.pyenv/versions/3.5.2/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/healther/.pyenv/versions/3.5.2/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/Users/healther/.pyenv/versions/3.5.2/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/Users/healther/.pyenv/versions/3.5.2/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/Users/healther/.pyenv/versions/3.5.2/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/Users/healther/.pyenv/versions/3.5.2/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
```

**Comment by alperyeg** [comment]
You could put the `urlretrieve` commands to a function, and call it in a try catch block, checking for URLError. 
Something like this: 
```python
from urllib.error import URLError
try: 
    download_fim()
except URLError:
   # or even a warning from warning module 
    print("Could not download fim.so. Please check if internet connection is available or the files exist.")
```

**Comment by dizcza** [comment]
The issue should be closed because it is resolved in the PRs, mentioned above.
Reopen if I'm wrong.
