### ISSUE TITLE
[BUG] Valid mode in CCH function for different t_start and t_stop

### ISSUE THREAD

**Issue by janlewen** [NeuralEnsemble/elephant#272]
Hi,
I have a probem with the window parameter "valid" in the function cross_correlation_histogram.

I think for this mode it is nessecary to give different long spiketrains, but then an Error is raised. Here one example code:
```
start = 0.0*s
end = 10.0*s
st2 = BinnedSpikeTrain(homogeneous_poisson_process(rate=10.0*Hz, t_start=0.0*s, t_stop=10.0*s), binsize = 10*ms)
st1 = BinnedSpikeTrain(homogeneous_poisson_process(rate=10.0*Hz, t_start=2.5*s, t_stop=7.5*s), binsize = 10*ms)

cch, bins = cross_correlation_histogram(st1, st2, window = "valid")
plt.bar(bins, np.concatenate(cch))
plt.show()
```

The Error message is:
```
Traceback (most recent call last):

  File "<ipython-input-10-92b03047740d>", line 1, in <module>
    runfile('/home/lewen/Dropbox/Masterarbeit/sandkasten.py', wdir='/home/lewen/Dropbox/Masterarbeit')

  File "/home/lewen/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/lewen/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/lewen/Dropbox/Masterarbeit/sandkasten.py", line 29, in <module>
    cch, bins = cross_correlation_histogram(st1, st2, window = "valid")

  File "/home/lewen/anaconda3/lib/python3.7/site-packages/elephant/spike_train_correlation.py", line 543, in cross_correlation_histogram
    raise AssertionError("Spike train must have same t start")

AssertionError: Spike train must have same t start
```

Expected behavior:
That the CCH is calculated like in numpy.correlate and the lags are given with quantities. Lag 0 would be the value if the smaller spiketrain is centered within the bigger one. And the difference in the starting times are ignored.

**Comment by dizcza** [comment]
We can do this either
1. Always pass mode='full' and then clip the result array to our valid window.
2. Ignore the differences in t_starts, calc the CCH and then shift the output array back, according to the diff in t_starts.
