### ISSUE TITLE
[Bug] GPU-accelerated ASSET tries to use a backend that is not present in the environment

### ISSUE THREAD

**Issue by kohlerca** [NeuralEnsemble/elephant#481]
Hello everyone!

I configured an environment to run ASSET using CUDA.

I tried to test it using the CPU first, by disabling the environment flag. The script fails because it tries to use OpenCL. However, OpenCL is not even present in the environment.

Looking into the code in `asset.py`, it seems that when getting the backend in the `_choose_backend` method, the existence of a valid backend is considered only for CUDA, and not for OpenCL. I could fix that by explicitly setting the `ELEPHANT_USE_OPENCL` environment variable to `'0'`, so that the default value `'1'` is not used in line 514. 

However, this is not good behavior, as it forces the user to set an environmental variable when it is obvious that a certain backend should not be used. 

**To reproduce the bug**

1. Setup the environment below (conda YAML).
```
name: cuda-asset
dependencies:
  - python = 3.10
  - pip
  - pip:
    - quantities
    - neo==0.10.2
    - nixio==1.5.3
    - elephant==0.11.1
    - jinja2>=2.11.2
    - scikit-learn>=0.23.12
    - statsmodels>=0.12.1
    - pycuda>=2020.1
```

2. Run an ASSET workflow (code and dataset are the same used in the Elephant tutorial):
```
import os
import quantities as pq
import neo
from elephant import asset


nix_dataset = "asset_showcase_500.nix"
bin_size = 3*pq.ms
kernel_width = 50*pq.ms
filter_shape = (11,3)
n_largest = 3
alpha = 0.99
max_distance = 11
min_neighbors = 10
stretch = 5
CUDA = False


print(f"Dataset: {nix_dataset}; CUDA: {CUDA}")

# Set CUDA flag
os.environ['ELEPHANT_USE_CUDA'] = '1' if CUDA else '0'

# Load data
with neo.NixIO(nix_dataset, 'ro') as f:
    block = f.read_block()
segment = block.segments[0]
spiketrains = segment.spiketrains

# Create ASSET object
asset_obj = asset.ASSET(spiketrains, bin_size=bin_size)

# Compute the intersection matrix
imat = asset_obj.intersection_matrix()

# Compute the probability matrix
pmat = asset_obj.probability_matrix_analytical(imat, kernel_width=kernel_width)

# Compute the joint probability matrix
jmat = asset_obj.joint_probability_matrix(pmat, filter_shape=filter_shape, n_largest=n_largest)

# Compute the mask matrix
mmat = asset_obj.mask_matrices([pmat, jmat], [alpha, alpha])

# Compute the cluster matrix
cmat = asset_obj.cluster_matrix_entries(mmat, max_distance=max_distance, min_neighbors=min_neighbors, stretch=stretch)

# Extract the SSEs
sses = asset_obj.extract_synchronous_events(cmat)

# Show results
print(sses)
```

**Output**
```
Dataset: /p/home/jusers/koehler4/jureca/data/asset_showcase_500.nix; CUDA: False
compute rates by boxcar-kernel convolution...
compute the prob. that each neuron fires in each pair of bins...
compute the probability matrix by Le Cam's approximation...
substitute 0.5 to elements along the main diagonal...
Traceback (most recent call last):
  File "/p/home/jusers/koehler4/jureca/projects/massive-asset/code/run_simple.py", line 63, in <module>
    main(dataset, CUDA=use_cuda)
  File "/p/home/jusers/koehler4/jureca/projects/massive-asset/code/run_simple.py", line 38, in main
    jmat = asset_obj.joint_probability_matrix(pmat, filter_shape=filter_shape,
  File "/p/home/jusers/koehler4/jureca/miniconda3/envs/massive-asset/lib/python3.10/site-packages/elephant/asset/asset.py", line 2272, in joint_probability_matrix
    pmat_neighb = pmat_neighb_obj.compute(pmat)
  File "/p/home/jusers/koehler4/jureca/miniconda3/envs/massive-asset/lib/python3.10/site-packages/elephant/asset/asset.py", line 1247, in compute
    lmat = backend(mat)
  File "/p/home/jusers/koehler4/jureca/miniconda3/envs/massive-asset/lib/python3.10/site-packages/elephant/asset/asset.py", line 1052, in pyopencl
    import pyopencl as cl
ModuleNotFoundError: No module named 'pyopencl'
```

**Expected behavior**
ASSET should not try to use a backend that is not configured in the environment.

**Environment**
 - OS (e.g., Linux): Rocky Linux release 8.5 (Green Obsidian)
 - How you installed elephant (`conda`, `pip`, source): pip
 - Python version: 3.10
 - `neo` python package version: 0.10.2
 - `elephant` python package version: 0.11.1

**Comment by Moritz-Alexander-Kern** [comment]
Hey @kohlerca ,

thanks for reporting this, I get the same output.

I agree, this seems to have originated in `_choose_backend`
https://github.com/NeuralEnsemble/elephant/blob/7f2a01cc50e36acdfc276cf359c430e9621de43d/elephant/asset/asset.py#L509-L520

The inline comments seem to indicate that the default behavior should be as you describe, but it seems to be implemented differently:


`use_opencl = int(os.getenv("ELEPHANT_USE_OPENCL", '1')) `

Here the default for `os.getenv` is  set to 1 (True), from [Python  docs](https://docs.python.org/3/library/os.html)
```
 os.getenv(key, default=None)

    Return the value of the environment variable key if it exists, or default if it doesn’t. key, default and the result are str.
```

Lets discuss this, spontaneously I can think of two things: - change the default behavior for openCL, introduce a check for backend openCL (similar to CUDA).
