### ISSUE TITLE
[Bug] Error in current_source_density.generate_lfp 

### ISSUE THREAD

**Issue by rcpeene** [NeuralEnsemble/elephant#546]
**Describe the bug**

When running the function `generate_lfp` with what I believe to be the intended usage, I received a runtime error and the program halts.

**To Reproduce**
1. Define an array xs to x coordinate values with a length of 2304
2. Run `generate_lfp(gauss_1d_dipole, xs)`
3. See the resulting error. (Traceback shown below)

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [22], line 1
----> 1 lfp = generate_lfp(gauss_1d_dipole, xs)

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\elephant\utils.py:80, in deprecated_alias.<locals>.deco.<locals>.wrapper(*args, **kwargs)
     77 @wraps(func)
     78 def wrapper(*args, **kwargs):
     79     _rename_kwargs(func.__name__, kwargs, aliases)
---> 80     return func(*args, **kwargs)

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\elephant\current_source_density.py:302, in generate_lfp(csd_profile, x_positions, y_positions, z_positions, x_limits, y_limits, z_limits, resolution)
    300 chrg_x = x
    301 csd = csd_profile(chrg_x)
--> 302 pots = integrate_1D(x_positions, chrg_x, csd, h)
    303 pots /= 2. * sigma  # eq.: 26 from Potworowski et al
    304 ele_pos = x_positions

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\elephant\current_source_density.py:263, in generate_lfp.<locals>.integrate_1D(x0, csd_x, csd, h)
    262 def integrate_1D(x0, csd_x, csd, h):
--> 263     m = np.sqrt((csd_x - x0) ** 2 + h ** 2) - abs(csd_x - x0)
    264     y = csd * m
    265     I = simps(y, csd_x)

ValueError: operands could not be broadcast together with shapes (50,) (2304,) 
```

**Expected behavior**
I expected the function to return an array of LFP values.

**Environment**
 - Windows 10:
 - Installed elephant with `pip install elephant`:
 - Python version: 3.9.10
 - neo==0.12.0
 - numpy==1.21.5
 - elephant==0.12.0

**Additional Context**
Running `generate_lfp(gauss_1d_dipole, xs, resolution=2304)` does run and return values. Although I'm unsure if this was the intentional usage.

**Comment by rcpeene** [comment]
printing `lfp` after the setting resolution to 2304 yields this;
```python
AnalogSignal with 1 channels of length 1; units mV; datatype float64 
annotations: {'coordinates': array([7648., 7651., 7660., ..., 7102., 7094., 7089.]) * mm}
sampling rate: 1.0 kHz
time: 0.0 s to 0.001 s
```

**Comment by Moritz-Alexander-Kern** [comment]
Hey @rcpeene ,
thanks for reporting this.
I was able to reproduce this with this minimal example:

```python
import numpy as np
from elephant.current_source_density import generate_lfp
from elephant.current_source_density_src.utility_functions import gauss_1d_dipole
# To Reproduce
# 1. Define an array xs to x coordinate values with a length of 2304
xs=np.linspace(0,1000, 2304)
# 2. Run generate_lfp(gauss_1d_dipole, xs)
lfp = generate_lfp(gauss_1d_dipole, xs)
# 3. See the resulting error. (Traceback shown below)
```
```
Traceback (most recent call last):
  File "current_source_density_lfp.py", line 11, in <module>
    lfp = generate_lfp(gauss_1d_dipole, xs)
  File "elephant/utils.py", line 80, in wrapper
    return func(*args, **kwargs)
  File "elephant/current_source_density.py", line 329, in generate_lfp
    pots = _integrate_1d(x_positions, chrg_x, csd, h)
  File "elephant/current_source_density.py", line 263, in _integrate_1d
    m = np.sqrt((csd_x - x0) ** 2 + h ** 2) - abs(csd_x - x0)
ValueError: operands could not be broadcast together with shapes (50,) (2304,) 
```

Running `generate_lfp(gauss_1d_dipole, xs, resolution=2304)` returns a `<class 'neo.core.analogsignal.AnalogSignal'>`, see [here](https://neo.readthedocs.io/en/stable/api_reference.html#neo.core.AnalogSignal) for documentation  (this is intended).

As far as I can see, the default value for the resolution is causing the problem here.

Does using a resolution of 2304 give you the result you expected?
If not, allow me some time to have a closer look.

**Comment by rcpeene** [comment]
Providing resolution of 2304 yields the value shown above. Running `estimate_csd(lfp, method="StandardCSD")` with the output from `generate_lfp` then yields the following error;

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [6], line 3
      1 xs = nwb.electrodes.x
      2 lfp = generate_lfp(gauss_1d_dipole, xs, res=2304)
----> 3 estimate_csd(lfp, method="StandardCSD")

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\elephant\utils.py:80, in deprecated_alias.<locals>.deco.<locals>.wrapper(*args, **kwargs)
     77 @wraps(func)
     78 def wrapper(*args, **kwargs):
     79     _rename_kwargs(func.__name__, kwargs, aliases)
---> 80     return func(*args, **kwargs)

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\elephant\current_source_density.py:137, in estimate_csd(lfp, coordinates, method, process_estimate, **kwargs)
    135     raise ValueError('Must specify a method of CSD implementation')
    136 if len(coordinates) != lfp.shape[1]:
--> 137     raise ValueError('Number of signals and coords is not same')
    138 for ii in coordinates:  # CHECK for Dimensionality of electrodes
    139     if len(ii) > 3:

ValueError: Number of signals and coords is not same
```

Is this a separate error, or related?

**Comment by Moritz-Alexander-Kern** [comment]
Hey @rcpeene ,

this seems to be a related error.

We might have found a solution, see the following example:

```python
import numpy as np
from elephant.current_source_density import generate_lfp, estimate_csd
from elephant.current_source_density_src.utility_functions import gauss_1d_dipole
# 1. Define an array xs to x coordinate values with a length of 2304
xs=np.linspace(0, 10, 2304).reshape(2304,1)

# 2. Run generate_lfp(gauss_1d_dipole, xs)
lfp = generate_lfp(gauss_1d_dipole, xs)

# 3. Run estimate_csd(lfp, method="StandardCSD")
csd=estimate_csd(lfp, method="StandardCSD")

# 4. Print the results
print(f"LFPs: {lfp}")
print(f"CSD estimate: {csd}")
```
Results:
```
discrete filter coefficients: 
b = [ 0.607 1.000 0.607 ],                
a = [ 2.213 ]
LFPs: [[-0.01483719 -0.01483286 -0.01482853 ...  0.0121921   0.01219087
   0.01218963]] mV
CSD estimate: [[-1.35188244e-04 -8.19956856e-05  2.30120206e-10 ... -4.06996957e-09
  -2.33711253e-05 -3.85287149e-05]] A/m**2
```

**Essentially, you can try to reshape the input `xs` to `(2304, 1)`  using  [`numpy.reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)**.

 As a followup I'm planning the following refactoring:
- provide a usage example in the documentation
- handle 1-dimensional arrays as inputs, no need to use reshape in the future
- add input tests
- add regression tests to avoid this issue in the future

Please let me know if this works for you and thanks again for reporting this :+1: .
